### ISSUE TITLE
Crashed when sync (Unhandled Exception: SerializationError)

### ISSUE THREAD

**Issue by thangmam** [cbl-dart/cbl-dart#349]
**Describe the bug**
Throws Unhandled Exception: SerializationError when sync

<details>
 <summary>Flutter console logs</summary>

 `#42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
 #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
 #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
 #45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
 #46     _StreamController._add (dart:async/stream_controller.dart:648:7)
 #47     _StreamController.add (dart:async/stream_controller.dart:596:5)#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
 #0      Channel.call.<anonymous closure>
 package:cbl/…/service/channel.dart:155
 <asynchronous suspension>
 #1      ProxyReplicator.create
 package:cbl/…/replication/proxy_replicator.dart:79
 <asynchronous suspension>
 #2      _HomeScreenState.build.<anonymous closure>
 package:couchbase_lite_flutter/screens/home_screen.dart:46
 <asynchronous suspension>`
</details

I have uploaded debug logs for each bug level and zipped.
[cbllogs.zip](https://github.com/cbl-dart/cbl-dart/files/8447578/cbllogs.zip)

**Environment (please complete the following information):**

 - OS: Windows/ Crashed on android too
 - `cbl`:
 - `cbl_flutter`:
 - `cbl_flutter_ce`:

**Comment by blaugold** [comment]
Thanks for reporting this. Unfortunately, the ZIP file is empty, and the stack trace seems to be incomplete. Could you provide a full stack trace? Since the exception is thrown while creating the `Replicator` it would also be helpful for me to see the `ReplicatorConfiguration`.

**Comment by thangmam** [comment]
Hello, sorry about the zip file empty. I didn't double check. Here is the logs from flutter console 

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SerializationError: No serializer registered for error:
Instance of 'CBLErrorException'
#0      throwCBLError
package:cbl_ffi/src/base.dart:234
#1      checkCBLError
package:cbl_ffi/src/base.dart:228
#2      CheckCBLErrorPointerExt.checkCBLError
package:cbl_ffi/src/base.dart:249
#3      ReplicatorBindings.createEndpointWithUrl.<anonymous closure>
package:cbl_ffi/src/replicator.dart:575
#4      runWithSingleFLString
package:cbl_ffi/src/utils.dart:72
#5      ReplicatorBindings.createEndpointWithUrl
package:cbl_ffi/src/replicator.dart:572
#6      _extension#5.createEndpoint
package:cbl/…/replication/ffi_replicator.dart:389
#7      FfiReplicator.create
package:cbl/…/replication/ffi_replicator.dart:80
#8      CblService._createReplicator
package:cbl/…/service/cbl_service.dart:571
#9      Channel.addCallEndpoint.<anonymous closure>
package:cbl/…/service/channel.dart:201
#10     Channel._handleCallRequest.<anonymous closure>
package:cbl/…/service/channel.dart:341
#11     new Future.sync (dart:async/future.dart:296:31)
#12     Channel._handleCallRequest
package:cbl/…/service/channel.dart:341
#13     Channel.open.<anonymous closure>.<anonymous closure>
package:cbl/…/service/channel.dart:266
#14     TracingDelegate.restoreTracingContext
package:cbl/src/tracing.dart:173
#15     _ServiceWorkerDelegate.initialize.<anonymous closure>
package:cbl/…/service/cbl_worker.dart:134
#16     Channel.open.<anonymous closure>
package:cbl/…/service/channel.dart:250
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#18     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#22     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#23     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#24     _ChunkConversionSinkTransformer.add
package:cbl/…/serialization/serialization_codec.dart:101
#25     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)

**Comment by thangmam** [comment]
Here is the replicator and its configuration.

> var db = await Database.openAsync('cbl');
            var r = await Replicator.create(
              ReplicatorConfiguration(
                database: db,
                target: UrlEndpoint(
                  Uri.parse('http://localhost:8091/test-bucket'),
                ),
              ),
            );
            await r.addChangeListener((change) {
              debugPrint('change listener : ${change.status}');
            });
            await r.start();
            await r.close();
            await db.close();

**Comment by thangmam** [comment]
Here is the zip file
[cbllogs.zip](https://github.com/cbl-dart/cbl-dart/files/8455145/cbllogs.zip)

**Comment by blaugold** [comment]
Thanks for the additional data.

The problem is the URL you're using for the `UrlEndpoint`. I think you're trying to connect directly to a Couchbase Server, instead of a Couchbase Sync Gateway, which is what you need to do. The Sync Gateway is a separate component that talks to the Couchbase Server. An URL to connect to a Sync Gateways looks something like this: `ws://localhost:4984/test-database`.

There is a bug here because you should get an exception with a proper description of the problem.

**Comment by thangmam** [comment]
You're right. the sync gateway url was the problem. Thank you. I got it working now.  Much appreciated
