### ISSUE TITLE
Adding a DocumentReplicationListener results in an unhandled exception from the replicator during processing.

### ISSUE THREAD

**Issue by markwigzell** [cbl-dart/cbl-dart#537]
Describe the bug
Whilst running the Replicator throws the log below. 

To Reproduce
Call Replicator.addDocumentReplicationListener with a listener.
The replicator tries to report following error: 

  Missing body of source revision '1980521-46c5486f35300d02bd2d0f14cb43b113' for delta

But then it gets an exception processing it.
As above.

Expected behavior

Should not throw exception, and should report error normally.

Environment (please complete the following information):

OS:
cbl: ^2.2.2
cbl_flutter: ^2.0.9
cbl_flutter_ee: ^2.2.2

Additional context

E/flutter (31740): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'int' is not a subtype of type 'CBLErrorCode' in type cast
E/flutter (31740): #0 _toCouchbaseLiteException (package:cbl/src/support/errors.dart:72:25)
E/flutter (31740): #1 CBLErrorExceptionExt.toCouchbaseLiteException (package:cbl/src/support/errors.dart:54:7)
E/flutter (31740): #2 _extension#4.toReplicatedDocument (package:cbl/src/replication/ffi_replicator.dart:378:16)
E/flutter (31740): #3 FfiReplicator._addDocumentReplicationListener.<anonymous closure>.<anonymous closure> (package:cbl/src/replication/ffi_replicator.dart:266:46)
E/flutter (31740): #4 MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
E/flutter (31740): #5 ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
E/flutter (31740): #6 new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
E/flutter (31740): #7 new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter (31740): #8 new List.of (dart:core-patch/array_patch.dart:47:28)
E/flutter (31740): #9 ListIterable.toList (dart:_internal/iterable.dart:214:7)
E/flutter (31740): #10 FfiReplicator._addDocumentReplicationListener.<anonymous closure> (package:cbl/src/replication/ffi_replicator.dart:266:70)
E/flutter (31740): #11 AsyncCallback._messageHandler.<anonymous closure> (package:cbl/src/support/async_callback.dart:149:37)
E/flutter (31740): #12 new Future.sync (dart:async/future.dart:305:31)
E/flutter (31740): #13 AsyncCallback._messageHandler (package:cbl/src/support/async_callback.dart:147:12)
E/flutter (31740): #14 _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (31740): #15 CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter (31740): #16 _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (31740): #17 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (31740): #18 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (31740): #19 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (31740): #20 _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (31740): #21 _StreamController.add (dart:async/stream_controller.dart:606:5)
E/flutter (31740): #22 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

**Comment by markwigzell** [comment]
I forgot to mention, that when debugging the point at which the exception is thrown, I saw that the "int' exception code was 31, and that there are only 30 CBL error code in the enum. So I think it is an issue of mis-matched error codes.

**Comment by markwigzell** [comment]
I guess I am not understanding how to update an issue. It seems it got marked as closed. This is NOT the case, the issue still occurs on my system. The bug is pretty easy see, its cast issue of int 30 to an undefined CBL error code. See the exception frame above. 
`package:cbl/src/support/errors.dart:54:7`

**Comment by blaugold** [comment]
Thanks for reporting this! I'm looking into it right now.
